name: $(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
variables:
- group: uipath-cicd

trigger:
- master

stages:
  - stage: Build
    displayName: Build artifacts and create change sets
    jobs:
    - job: build
      pool:
        vmImage: 'windows-latest'
      container:
        image: $(containerRegistry).azurecr.io/$(repositoryName):latest
        endpoint: demovmcontainer
      steps:
      - script: c:\UiPath\Robot\UiRobot.exe -pack $(Build.SourcesDirectory)\project.json -o $(Build.ArtifactStagingDirectory)\ -version 1.0.$(Build.BuildId)
        displayName: Build artifact
        name: buildArtifact
      - powershell: |
          Import-Module UiPath.PowerShell
          $token = Get-UiPathAuthToken -URL $(orchUrl) -Username $(uatUsername) -Password $(uatPassword) -TenantName $(uatTenantName)

          $temp = "C:\scripts"
          $link = "https://raw.githubusercontent.com/AndreiBarbuOz/uipath-config/master/cicd-lib.ps1"
          $file = "cicd-lib.ps1"
          New-Item $temp -ItemType directory
          Set-Location -Path $temp
          Set-ExecutionPolicy Unrestricted -force
          Invoke-WebRequest -Uri $link -OutFile $file
          . C:\scripts\cicd-lib.ps1

          $configContent = Get-Content -Path $(Build.SourcesDirectory)\config\config.json | ConvertFrom-Json
          
          $assetChangeSet = Get-AssetChanges -DesiredAssetState $configContent.assets -Token $token 
          $changeSet = @{"assets"=$assetChangeSet}

          $changeSet | ConvertTo-Json -Depth 5 | Out-File -FilePath $(Build.ArtifactStagingDirectory)\change-set.json
        displayName: Create the change set
        name: buildChangeSet
      - publish: $(Build.ArtifactStagingDirectory)
        artifact: drop
        displayName: Publish build artifacts
  - stage: DeployUAT
    dependsOn: Build
    condition: succeeded()
    displayName: Verify change sets, Deploy to UAT
    jobs:
    - deployment: deployUAT
      pool:
        vmImage: 'windows-latest'
      container:
        image: $(containerRegistry).azurecr.io/$(repositoryName):latest
        endpoint: demovmcontainer
      environment: 'uat'
      strategy:
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: drop
                displayName: Download build artifacts
              - powershell: |
                  Import-Module UiPath.PowerShell
                  $token = Get-UiPathAuthToken -URL $(orchUrl) -Username $(uatUsername) -Password $(uatPassword) -TenantName $(uatTenantName)
                  Get-ChildItem -Path $(Pipeline.Workspace)\drop -Filter *.nupkg | ForEach-Object {Add-UiPathPackage -PackageFile $_.FullName -AuthToken $token}
                displayName: Upload package to UAT 
                name: deployUatPackage
              - powershell: |
                  Import-Module UiPath.PowerShell
                  $token = Get-UiPathAuthToken -URL $(orchUrl) -Username $(uatUsername) -Password $(uatPassword) -TenantName $(uatTenantName)
        
                  $temp = "C:\scripts"
                  $link = "https://raw.githubusercontent.com/AndreiBarbuOz/uipath-config/master/cicd-lib.ps1"
                  $file = "cicd-lib.ps1"
                  New-Item $temp -ItemType directory
                  Set-Location -Path $temp
                  Set-ExecutionPolicy Unrestricted -force
                  Invoke-WebRequest -Uri $link -OutFile $file
                  . C:\scripts\cicd-lib.ps1

                  $changeSetContent = Get-Content -Path $(Pipeline.Workspace)\drop\change-set.json | ConvertFrom-Json
                  $changeSetContent

                  Set-AssetChanges -Token $token -DesiredAssetState $changeSetContent.assets
                displayName: Apply change set to UAT
                name: deployUatChangeSet
  - stage: DeployProd
    dependsOn: DeployUAT
    condition: succeeded()
    displayName: Verify change sets, Deploy to Prod
    jobs:
    - deployment: deployProd
      pool:
        vmImage: 'windows-latest'
      container:
        image: $(containerRegistry).azurecr.io/$(repositoryName):latest
        endpoint: demovmcontainer
      environment: 'prod'
      strategy:
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: drop
                displayName: Download build artifacts
              - powershell: |
                  Import-Module UiPath.PowerShell
                  $token = Get-UiPathAuthToken -URL $(orchUrl) -Username $(prodUsername) -Password $(prodPassword) -TenantName $(prodTenantName)
                  Get-ChildItem -Path $(Pipeline.Workspace)\drop -Filter *.nupkg | ForEach-Object {Add-UiPathPackage -PackageFile $_.FullName -AuthToken $token}
                displayName: Upload package to Prod 
                name: deployProdPackage
              - powershell: |
                  Import-Module UiPath.PowerShell
                  $token = Get-UiPathAuthToken -URL $(orchUrl) -Username $(prodUsername) -Password $(prodPassword) -TenantName $(prodTenantName)
        
                  $temp = "C:\scripts"
                  $link = "https://raw.githubusercontent.com/AndreiBarbuOz/uipath-config/master/cicd-lib.ps1"
                  $file = "cicd-lib.ps1"
                  New-Item $temp -ItemType directory
                  Set-Location -Path $temp
                  Set-ExecutionPolicy Unrestricted -force
                  Invoke-WebRequest -Uri $link -OutFile $file
                  . C:\scripts\cicd-lib.ps1

                  $changeSetContent = Get-Content -Path $(Pipeline.Workspace)\drop\change-set.json | ConvertFrom-Json
                  $changeSetContent

                  Set-AssetChanges -Token $token -DesiredAssetState $changeSetContent.assets
                displayName: Apply change set to Prod
                name: deployProdChangeSet
