variables:
- group: uipath-cicd

trigger:
- master

jobs:
  - job: build_and_upload
    pool:
      vmImage: 'windows-latest'
    container:
      image: $(containerRegistry).azurecr.io/$(repositoryName):latest
      endpoint: demovmcontainer
    steps:
    - script: c:\UiPath\Robot\UiRobot.exe -pack .\project.json -o .
    - script: dir /s
    - powershell: |
        Import-Module UiPath.PowerShell
        $token = Get-UiPathAuthToken -URL $(orchUrl) -Username username -Password password -TenantName tenantName
#        $project = Get-Content .\MockProcess\project.json | Out-String | ConvertFrom-Json
#        Get-ChildItem -Path . -Filter *.nupkg | ForEach-Object {Add-UiPathPackage -PackageFile $_.FullName -AuthToken $token}
#        $package = Get-UiPathPackage -id $project.name -AuthToken $token
#        $testEnv = Get-UiPathEnvironment -name UnitTesting -AuthToken $token
#        $process = Add-UiPathProcess -Name ("UnitTest-" + $package.Id) -Environment $testEnv -Package $package -AuthToken $token
#        Start-UiPathJob -RobotCount 1 -Process $process -AuthToken $token
#      displayName: 'Run a one-line script'
