variables:
- group: uipath-cicd

trigger:
- master

jobs:
  - job: build_and_upload
    pool:
      vmImage: 'windows-latest'
    container:
      image: $(containerRegistry).azurecr.io/$(repositoryName):latest
      endpoint: demovmcontainer
    steps:
    - script: c:\UiPath\Robot\UiRobot.exe -pack $(Build.SourcesDirectory)\project.json -o $(Build.ArtifactStagingDirectory)\
    - powershell: |
        Import-Module UiPath.PowerShell
        Get-UiPathAuthToken -URL $(orchUrl) -Username $(username) -Password $(password) -TenantName $(tenantName) -Session
        Get-ChildItem -Path $(Build.ArtifactStagingDirectory) -Filter *.nupkg | ForEach-Object {Add-UiPathPackage -PackageFile $_.FullName}
        $package = Get-UiPathPackage -id $project.name 

        Get-UiPathRobot | Format-Table
        Get-UiPathProcess | Format-Table
        Get-UiPathPackage | Format-Table
        Get-UiPathPackageVersion -Package $package | Format-Table
      displayName: 'Build package'
